Update links to language models in README
m-bain/whisperX pull request #757
Opened 2024-03-25 16:01 UTC by MJochim

The list of languages is no longer in transcribe.py, it’s been moved to alignment.py. I have created a new permalink.

I would suggest another change: remove

> , and use the wihisper `--model large`

from line 141. It seems to work with `--model small` just as well. But I am not sure why it was there in the first place, so I haven’t included the change in this PR.

2024-04-14 12:38 UTC, deep-pipeline commented
@m-bain this PR 757 from @MJochim seems to me to supercede PR #522 (which simply changes the README list of language codes.) and instead it directs people to look at the code for the HF related models. 

That's probably a bit less repo-browser / user-friendly than updating a full language code list, but is may be more sustainable for README accuracy and developer helpful.

2024-12-16 09:55 UTC, Barabazs requested changes
Thank you for your contribution.

2024-12-16 09:55 UTC, Barabazs commented on README.md
> +Currently default models provided for `{en, fr, de, es, it}` via torchaudio pipelines and [25 other languages via huggingface](https://github.com/m-bain/whisperX/blob/f2da2f858e99e4211fe4f64b5f2938b0
```suggestion
Currently default models provided for `{en, fr, de, es, it}` via torchaudio pipelines and many other languages via Hugging Face. Please find the list of currently supported languages under `DEFAULT_ALIGN_MODELS_HF` on [alignment.py](https://github.com/m-bain/whisperX/blob/main/whisperx/alignment.py). If the detected language is not in this list, you need to find a phoneme-based ASR model from [huggingface model hub](https://huggingface.co/models) and test it on your data.
```

2024-12-16 09:55 UTC, Barabazs commented on README.md
> +Currently default models provided for `{en, fr, de, es, it}` via torchaudio pipelines and [25 other languages via huggingface](https://github.com/m-bain/whisperX/blob/f2da2f858e99e4211fe4f64b5f2938b0
The list of supported languages is often updated and this change would allow us to leave the doc unchanged.

2025-01-17 07:47 UTC, merged