Added local_files_only option on whisperx.load_model for offline mode
m-bain/whisperX pull request #867
Opened 2024-08-25 05:27 UTC by RoqueGio

Adds the parameter local_files_only (default False for consistency) to whisperx.load_model so that the user can avoid downloading the file and return the path to the local cached file if it exists.

2024-10-01 18:05 UTC, madriss reviewed
Added local files only mode

2025-01-01 11:51 UTC, Barabazs requested changes
Just one minor change request please.

2025-01-01 11:51 UTC, Barabazs commented on whisperx/asr.py
> +        local_files_only: Optional[bool] - If `True`, avoid downloading the file and return the path to the local cached file if it exists.
```suggestion
        local_files_only: bool - If `True`, avoid downloading the file and return the path to the local cached file if it exists.
```
Optional[...] is for arguments that default to None, which is not the case here.

2025-01-01 12:13 UTC, Barabazs commented on whisperx/asr.py
> +        local_files_only: Optional[bool] - If `True`, avoid downloading the file and return the path to the local cached file if it exists.
nvm, I didn't realise the PR was so old. I'll push the change

2025-01-01 12:13 UTC, Barabazs approved these changes

2025-01-01 12:16 UTC, merged

2025-01-01 12:17 UTC, Barabazs commented
Thank you for your contribution @RoqueGio !